# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - manipulator_controller

  manipulator_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_1_joint
      - wrist_1_joint
      - wrist_2_joint
    action_ns: follow_joint_trajectory
    default: true